site_name: ConsistencyBench
#site_url: https://geico.visualstudio.com/ML%20and%20DS%20Capabilities/_git/RAIModelDiagnosis
nav:
  - Home: index.md
  - UserGuide: userguide.md
  # - Packages:
  #     - Classification: classification.md
  #     - Regression: regression.md
  - About: about.md
theme:
  name: readthedocs

plugins:
  - mkdocstrings

#  features:
#    - navigation.tabs
#    - navigation.sections
#    - toc.integrate
#    - navigation.top
#    - search.suggest
#    - search.highlight
#    - content.tabs.link
#    - content.code.annotation
#    - content.code.copy
#  language: en
#  palette:
#    - scheme: default
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to dark mode
#      primary: teal
#      accent: purple
#    - scheme: slate
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode
#      primary: teal
#      accent: lime
